# Simulation parameters
WORLD_WIDTH = 2000
WORLD_HEIGHT = 2000
NUM_AGENTS = 1200

# Flocking parameters
MAX_FORCE = 10.0
SEPARATION_DISTANCE = 55.0
ALIGNMENT_DISTANCE = 30.0
COHESION_DISTANCE = 50.0

SEPARATION_WEIGHT = 40
ALIGNMENT_WEIGHT = 20
COHESION_WEIGHT = 150

CENTER_ATTRACTION_WEIGHT = 50  # この値は調整可能です
CONFINEMENT_WEIGHT = 30.0  # この値は調整可能です

# Box2D physics parameters
# Agent parameters
LINEAR_DAMPING = .5 #線形減衰
AGENT_RADIUS = 5 
AGENT_MASS = 2
AGENT_FRICTION = 0.5
AGENT_DENSITY = 1 #密度
AGENT_RESTITUTION = 1  # 弾力

# Simulation speed
RENDER_FPS = 240
DT = 1 / 30

# Colors
BACKGROUND_COLOR = (0, 0, 0)  # White
AGENT_COLOR = (255, 255, 255)  # Black

# Initial velocity range
INITIAL_VELOCITY_MIN = -100
INITIAL_VELOCITY_MAX = 100

